AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 900
    MemorySize: 7168
Parameters:
   Stage:
      Type: String
      Default: dev
Resources:
  TestPVAutomation:
    Type: AWS::Serverless::Function
    Properties:
      FunctionUrlConfig:
        AuthType: NONE
      PackageType: Image
      Architectures:
        - x86_64
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: python3.9-v1
